- app/assets/stylesheets/application.css
- app/views/layouts/application.html.erb
> header追加（git練習用）

- app/assets/stylesheets/application.css
- app/views/layouts/application.html.erb
- app/views/posts/index.html.erb
- app/views/posts/new.html.erb
新規投稿、投稿一覧ページのタイトルに共通のクラスを付けました。
全ページ共通のヘッダーを仮作成しました。
> Header edit

- practice.html
> 練習中です。practice.htmlを作成しました。byたかひろ

- Gemfile
- Gemfile.lock
- app/models/user.rb
- db/migrate/20200622105712_add_password_digest_to_users.rb
- db/schema.rb
- spec/factories/users.rb
- spec/models/user_spec.rb
文字数の検証です。
テストを書き、バリデーションを実装しました。
> Validates length

- app/assets/stylesheets/application.css
- app/views/layouts/application.html.erb
【削除したコード】
以前gitの動作確認のために記述したコードを削除しました。
【追加したコード】
新たにMemopyの仕様書に沿ってヘッダー部分をコーディングしました。
レスポンシブ対応可です。
> Memopyの仕様書に沿ってヘッダーを作成。

- app/controllers/users_controller.rb
- config/routes.rb
テストも書きたかったのですがテスト文が思いつかず断念しました…。
> ユーザー新規登録機能

- app/assets/stylesheets/application.css
- app/views/layouts/application.html.erb
画面スクロール時も常時フッターが画面下部に表示される不具合が発覚したため、
ページ最下部までスクロールしないと表示しないように変更。
> フッターの固定方法変更。

- app/assets/stylesheets/users/new.css
- app/views/users/new.html.erb
前ブランチでけんけんさんの#23の変更を破棄してしまった原因のログが見つからず、仮で新しいブランチとして立てました。
> 【最設】新規登録画面の作成

- app/assets/stylesheets/application.css
半角スペース4個分から2個分に変更しています。
及び、新規登録ページのコンテンツが重なる不具合が発生していたため、
フッターのz-indexを10に変更しています。
> 【修正案件】フッターのインデントを整形しました。

- app/controllers/friends_controller.rb
- app/controllers/sessions_controller.rb
- app/controllers/users_controller.rb
- app/helpers/sessions_helper.rb
- app/views/layouts/application.html.erb
フラッシュメッセージの実装です。
- ログイン
- 新規登録（名前、メールアドレス、パスワードのエラーメッセージをひとつずつ出したかったのですがつまずいたので別プルリクにしようと思います。）
- 人物追加、削除
sessions_helper.rb のlog_outメソッドが2つあることに気づいたので削除しました。
URLを直接入力すると該当ページが見れてしまうエラーを対策するlogged_in_userメソッドも実装しています。これは次のプルリクで使いますがフラッシュだったので先に実装しました。
> フラッシュメッセージの実装

- app/assets/javascripts/friends.js
- app/assets/stylesheets/friends.css
- app/views/friends/index.html.erb
friends.cssのpaddingが一部適用されていなかったので"px"を記載し適用されるようにしました。
> JSの記述をhtml.erbに変更

- app/assets/stylesheets/application.css
- app/assets/stylesheets/friends.css
- app/views/layouts/application.html.erb
全ページ共通でヘッダーの直下に表示されるようにフラッシュメッセージ表示位置を指定しました。
お手隙の際にご確認よろしくお願いします。
> フラッシュメッセージの表示位置を指定しました

- app/models/friend.rb
- app/models/friends_detail.rb
- db/migrate/20200703094957_create_friends_details.rb
- db/schema.rb
- spec/factories/friends.rb
- spec/factories/friends_details.rb
- spec/models/friend_spec.rb
- spec/models/friends_detail_spec.rb
DB設計をもとにfriends_detailモデルを作成しました。
存在性のバリデーションも実装しています。
> friends_detailモデルを作成

- app/assets/stylesheets/users/new.css
スマホサイズに縮めた時の挙動を
「labelとinputの部分が縦並びになる」ように設定。
CSS内の、「marginの方向をbottom方向に揃える」
「不必要と感じた記述を削除する」などの微調整
を行いました。
> ログイン、新規登録画面のフォーム部分のレスポンシブ化と微調整。

- app/controllers/friends_details_controller.rb
- app/views/friends/show.html.erb
friends_detailを削除できるようにdestroyアクションを追加しました。
> friends_detailのdelete

- app/views/layouts/application.html.erb
https://github.com/kenkeeeenbbt/memopy/issues/56
こちらのイシューに取り組みました！
ご確認よろしくお願いします！
> ヘッダーの「ようこそゲストさん」をログインユーザー名に動的に変更

- app/views/layouts/application.html.erb
> ヘッダーとフッターにマイページを追加

- app/assets/stylesheets/application.css
- app/views/layouts/application.html.erb
> フラッシュメッセージを自動的に削除するJSを実装しました。

- app/assets/stylesheets/application.css
- app/assets/stylesheets/users/new.css
- app/views/friends/new.html.erb
- app/views/sessions/new.html.erb
- app/views/users/new.html.erb
レスポンシブ完了、JavaScriptファイルは後で作成し読み込む形にします。
> フォーカスされると上にラベルっぽくなるプレースホルダーフェイク

- app/assets/stylesheets/users/new.css
- app/views/friends/new.html.erb
- app/views/sessions/new.html.erb
- app/views/users/new.html.erb
- config/initializers/assets.rb
申し訳ありません！ブランチ切って作業するべきでしたが、二つの機能分のプルリクになってしまい、粒度が大きくなってしまいました。
すいませんがお手隙の際にご確認お願いします。
> ラベルの横に「必須」タグと、ログイン状態維持のチェックボックス 拡大

- app/controllers/friends_controller.rb
- app/views/friends/edit.html.erb
- app/views/friends/index.html.erb
- app/views/friends/show.html.erb
friendの名前を編集する機能をつけました。
一覧、詳細画面からアクセスできるようにしています。
> friendのupdate

- app/assets/stylesheets/friends.css
- app/views/friends/show.html.erb
- app/views/layouts/application.html.erb
レイアウトの骨組みが出来たのでお手隙の際にご確認をお願いいたします。
> friends_detailのHTML,CSSをコーディングしました。

- app/assets/stylesheets/friends.css
- app/views/friends/index.html.erb
人物名編集機能追加に伴い、編集画面へのボタンと人物削除のボタンを実装しました。
> 人物名編集ボタン、人物削除ボタンの実装

- app/assets/stylesheets/friends.css
- app/views/friends_details/new.html.erb
friends-detailの新規登録画面をコーディングしました。
ご確認お願いします！
> friends-detailの新規登録画面をコーディングしました

- app/controllers/users_controller.rb
- app/views/users/show.html.erb
userのdelete機能を追加しました！
マイページから選択できるようにしてあります。
> userのdelete

- app/views/friends_details/edit.html.erb
- app/views/friends_details/new.html.erb
ベースとなる部分は新規登録画面と共通です。
お手隙の際にご確認お願い致します🙇‍♂️
> friends-detailの編集画面をコーディングしました

- app/views/friends/edit.html.erb
- app/views/sessions/new.html.erb
> ログイン＞人物リスト＞編集　のコーディング

- app/assets/stylesheets/application.css
- app/assets/stylesheets/users.scss
- app/assets/stylesheets/users/users.css
- app/views/users/show.html.erb
> ユーザー詳細画面のマークアップをしました。

- app/assets/stylesheets/friends.css
- app/controllers/friends_controller.rb
- app/views/friends/edit.html.erb
- app/views/friends/index.html.erb
- app/views/friends/new.html.erb
- app/views/layouts/application.html.erb
- app/views/sessions/new.html.erb
- app/views/users/edit.html.erb
> アプリ全体でフォントの色を統一しました。

- app/assets/stylesheets/friends.css
- app/views/friends/index.html.erb
> 友達名変更ページへのボタンのフォントサイズを修正しました。

- app/controllers/sessions_controller.rb
- app/models/user.rb
- app/views/sessions/new.html.erb
- config/routes.rb
ゲストユーザーとしてログインする機能をつけました。
app/models/user.rb はインデントの修正とself.guestメソッドを追加しています。
> ゲストユーザーとしてログイン

- app/assets/stylesheets/users/new.css
通常ログインボタンとゲストログインボタンの間隔を広げました。
> ゲストログインボタンのCSS修正

- app/controllers/home_controller.rb
- app/views/layouts/application.html.erb
- config/routes.rb
Memopyの概要紹介ページへアクセス出来るように以下3点実施しました。
・ルーティングの設定
・Homeコントローラ作成しaboutアクション追加
・ヘッダー部分のlink_toタグの設定
> 「Memopyとは」ページへアクセス出来るように設定
